# Generated by Django 5.0.6 on 2024-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("something", models.CharField(max_length=255)),
                ("something2", models.CharField(max_length=255)),
                ("something3", models.CharField(max_length=255)),
                ("something4", models.CharField(max_length=255)),
            ],
        ),
    ]
