# Generated by Django 5.0.6 on 2024-06-23 16:42

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_drive", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="folder",
            managers=[
                ("children", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="user_drive.folder",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files/"),
        ),
    ]
