# Generated by Django 5.0.6 on 2024-06-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_drive", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(blank=True, upload_to="files/"),
        ),
    ]
