# Generated by Django 5.0.6 on 2024-06-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_drive", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="nestedFolder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="user_drive.folder",
            ),
        ),
    ]
