# Generated by Django 5.0.6 on 2024-06-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_drive", "0002_alter_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files/"),
        ),
    ]
