# Generated by Django 5.0.6 on 2024-06-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_drive", "0002_alter_folder_managers_file_folder_alter_file_file"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="folder",
            managers=[],
        ),
    ]
