# Generated by Django 5.0.6 on 2024-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_drive", "0002_alter_folder_nestedfolder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="folder",
            old_name="nestedFolder",
            new_name="parent",
        ),
        migrations.AddField(
            model_name="folder",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="folder",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
