# Generated by Django 5.0.6 on 2024-06-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_drive", "0003_alter_folder_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="folder",
        ),
    ]
