# Generated by Django 5.0.6 on 2024-06-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_drive", "0004_remove_file_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subfolders",
                to="user_drive.folder",
            ),
        ),
    ]
