# Generated by Django 5.0.6 on 2024-06-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_drive", "0006_folder_drive_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="drive_parent",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="DriveParent",
                to="user_drive.drive",
            ),
        ),
    ]
