# Generated by Django 5.0.6 on 2024-06-19 10:22

import django.db.models.deletion
import user_drive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_drive", "0007_alter_folder_drive_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="drive_parent",
            field=models.ForeignKey(
                default=user_drive.models.Folder.get_default_drive,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="FolderDrive",
                to="user_drive.drive",
            ),
        ),
    ]
